(self.AMP=self.AMP||[]).push({n:"amp-user-notification",v:"1903281741200",f:(function(AMP,_){
var h,k="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var n;a:{var p={a:!0},q={};try{q.__proto__=p;n=q.a;break a}catch(a){}n=!1}l=n?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var r=l;function t(){var a,b;this.promise=new Promise(function(c,g){a=c;b=g});this.resolve=a;this.reject=b};function u(){this.h=0;this.R=Promise.resolve();this.O=function(){};this.P=function(){}}u.prototype.onQueueEmpty=function(a){this.O=a;0==this.h&&a()};u.prototype.onQueueNotEmpty=function(a){this.P=a;0<this.h&&a()};u.prototype.registerUI=function(a){var b=this;0==this.h&&this.P();this.h++;var c=this.R.then(function(){return a().then(function(){b.h--;0==b.h&&b.O()})});return this.R=c};function v(a){for(var b=null,c="",g=0;g<arguments.length;g++){var d=arguments[g];if(d instanceof Error&&!b){b=void 0;var e=Object.getOwnPropertyDescriptor(d,"message");if(e&&e.writable)b=d;else{e=d.stack;var f=Error(d.message);for(b in d)f[b]=d[b];f.stack=e;b=f}}else c&&(c+=" "),c+=d}b?c&&(b.message=c+": "+b.message):b=Error(c);return b}function w(a){var b=v.apply(null,arguments);setTimeout(function(){self.reportError(b);throw b;})}self.log=self.log||{user:null,dev:null,userForEmbed:null};var x=self.log;
function y(){if(!x.user)throw Error("failed to call initLogConstructor");return x.user}function z(){if(x.dev)return x.dev;throw Error("failed to call initLogConstructor");}function A(a,b,c,g,d){return y().assert(a,b,c,g,d,void 0,void 0,void 0,void 0,void 0,void 0)};function B(a){var b,c=a.ownerDocument.defaultView,g=c!=(c.__AMP_TOP||c);if(g){if(C(c,"url-replace")){var d=D(c,"url-replace");if(d)return d}if(!b)return null}a=E(a);a=F(a);return C(a,"url-replace")?D(a,"url-replace"):null}function G(a,b){a=a.__AMP_TOP||a;return D(a,b)}function E(a){return a.nodeType?G((a.ownerDocument||a).defaultView,"ampdoc").getAmpDoc(a):a}function F(a){a=E(a);return a.isSingleDoc()?a.win:a}
function D(a,b){C(a,b);var c=H(a);a=c[b];a.obj||(a.obj=new a.ctor(a.context),a.ctor=null,a.context=null,a.resolve&&a.resolve(a.obj));return a.obj}function I(a,b){var c=J(a,b);if(c)return c;a=H(a);a[b]=K();return a[b].promise}function J(a,b){var c=H(a)[b];if(c){if(c.promise)return c.promise;D(a,b);return c.promise=Promise.resolve(c.obj)}return null}function H(a){var b=a.services;b||(b=a.services={});return b}function C(a,b){a=a.services&&a.services[b];return!(!a||!a.ctor&&!a.obj)}
function K(){var a=new t,b=a,c=b.promise,g=b.resolve;b=b.reject;c.catch(function(){});return{obj:null,promise:c,resolve:g,reject:b,context:null,ctor:null}};/*
 https://mths.be/cssescape v1.5.1 by @mathias | MIT license */
function L(a){return a||{}};function M(a){var b=J(F(a),"geo");if(b)return b;var c=E(a);return c.whenBodyAvailable().then(function(){var a=c.win;var b=c.win.document.head;if(b){var e=[];b=b.querySelectorAll("script[custom-element]");for(var f=0;f<b.length;f++)e.push(b[f].getAttribute("custom-element"))}else e=[];a=e.includes("amp-geo")?G(a,"extensions").waitForExtension(a,"amp-geo"):Promise.resolve();return a}).then(function(){return J(F(a),"geo")})};function N(){var a=100;this.U=a;this.C=this.G=0;this.o=Object.create(null)}N.prototype.has=function(a){return!!this.o[a]};N.prototype.get=function(a){var b=this.o[a];if(b)return b.access=++this.C,b.payload};N.prototype.put=function(a,b){this.has(a)||this.G++;this.o[a]={payload:b,access:this.C};if(!(this.G<=this.U)){z().warn("lru-cache","Trimming LRU cache");a=this.o;var c=this.C+1,g;for(g in a){var d=a[g].access;if(d<c){c=d;var e=g}}void 0!==e&&(delete a[e],this.G--)}};L({c:!0,v:!0,a:!0,ad:!0,action:!0});var O,P;
function Q(a,b){var c=void 0===c?"source":c;A(null!=a,"%s %s must be available",b,c);var g=a;a=g;if("string"==typeof a){O||(O=self.document.createElement("a"),P=self.UrlCache||(self.UrlCache=new N));var d=P,e=O;if(d&&d.has(a))a=d.get(a);else{e.href=a;e.protocol||(e.href=e.href);var f={href:e.href,protocol:e.protocol,host:e.host,hostname:e.hostname,port:"0"==e.port?"":e.port,pathname:e.pathname,search:e.search,hash:e.hash,origin:null};"/"!==f.pathname[0]&&(f.pathname="/"+f.pathname);if("http:"==f.protocol&&
80==f.port||"https:"==f.protocol&&443==f.port)f.port="",f.host=f.hostname;f.origin=e.origin&&"null"!=e.origin?e.origin:"data:"!=f.protocol&&f.host?f.protocol+"//"+f.host:f.href;d&&d.put(a,f);a=f}}(d="https:"==a.protocol||"localhost"==a.hostname)||(a=a.hostname,d=a.length-10,d=0<=d&&a.indexOf(".localhost",d)==d);A(d||/^(\/\/)/.test(g),'%s %s must start with "https://" or "//" or be relative and served from either https or from localhost. Invalid value: %s',b,c,g)};function R(a){a=AMP.BaseElement.call(this,a)||this;a.J=null;a.m=null;var b=new t;a.K=b.promise;a.L=b.resolve;a.l=null;a.F=!1;a.A=null;a.B=null;a.w=null;a.j=null;a.H="";a.I=null;a.T=null;return a}var S=AMP.BaseElement;R.prototype=k(S.prototype);R.prototype.constructor=R;if(r)r(R,S);else for(var T in S)if("prototype"!=T)if(Object.defineProperties){var U=Object.getOwnPropertyDescriptor(S,T);U&&Object.defineProperty(R,T,U)}else R[T]=S[T];R.Z=S.prototype;h=R.prototype;h.isAlwaysFixed=function(){return!0};
h.buildCallback=function(){var a=this,b=this.getAmpDoc();this.T=B(this.element);this.I=I(F(this.element),"storage");this.m=A(this.element.id,"amp-user-notification should have an id.");this.H="amp-user-notification:"+this.m;this.A=this.element.getAttribute("data-show-if-geo");this.B=this.element.getAttribute("data-show-if-not-geo");(this.j=this.element.getAttribute("data-show-if-href"))&&Q(this.j,this.element);A(1>=!!this.j+!!this.A+!!this.B,'Only one "data-show-if-*" attribute allowed');this.A&&
(this.w=V(this,this.A,!0));this.B&&(this.w=V(this,this.B,!1));(this.l=this.element.getAttribute("data-dismiss-href"))&&Q(this.l,this.element);var c=this.element.getAttribute("role");c||this.element.setAttribute("role","alert");var g=this.element.getAttribute("data-persist-dismissal");this.F="false"!=g&&"no"!=g;this.registerDefaultAction(function(){return a.dismiss(!1)},"dismiss");this.registerAction("optoutOfCid",function(){return W(a)});var d=I(F(b),"userNotificationManager");d.then(function(b){b.registerUserNotification(a.m,
a)})};function V(a,b,c){return M(a.element).then(function(a){A(a,"requires <amp-geo> to use promptIfUnknownForGeoGroup");var d=b.split(/,\s*/).filter(function(b){return 2==a.isInCountryGroup(b)});return!(c?!d.length:d.length)})}
function X(a,b){var c=a.j;return a.T.expandUrlAsync(c).then(function(c){var d={elementId:a.m,ampUserId:b};var e=[];for(m in d){var f=d[m];if(null!=f)if(Array.isArray(f))for(var g=0;g<f.length;g++){var aa=f[g];e.push(encodeURIComponent(m)+"="+encodeURIComponent(aa))}else e.push(encodeURIComponent(m)+"="+encodeURIComponent(f))}d=e.join("&");e=c;if(d){e=e.split("#",2);var m=e[0].split("?",2);d=m[0]+(m[1]?"?"+m[1]+"&"+d:"?"+d);d+=e[1]?"#"+e[1]:""}else d=e;return d})}
h.V=function(a){var b=this;this.J=a;return X(this,a).then(function(a){var c={credentials:"include",requireAmpResponseSourceOrigin:!1};return G(b.win,"xhr").fetchJson(a,c).then(function(a){return a.json()})})};function ba(a){var b=a.element.getAttribute("enctype")||"application/json;charset=utf-8";G(a.win,"xhr").fetchJson(a.l,{method:"POST",credentials:"include",requireAmpResponseSourceOrigin:!1,body:L({elementId:a.m,ampUserId:a.J}),headers:{"Content-Type":b}})}
h.X=function(a){A("boolean"==typeof a.showNotification,'`showNotification` should be a boolean. Got "%s" which is of type %s.',a.showNotification,typeof a.showNotification);a.showNotification||this.L();return Promise.resolve(a.showNotification)};function W(a){return I(F(a.element),"cid").then(function(a){return a.optOut()}).then(function(){return a.dismiss(!1)},function(b){z().error("amp-user-notification","Failed to opt out of Cid",b);a.dismiss(!0)})}
function ca(a){return I(F(a.element),"cid").then(function(b){return b.get({scope:"amp-user-notification",createCookieIfNotPresent:!0},Promise.resolve(),a.K)})}h.shouldShow=function(){var a=this;return this.isDismissed().then(function(b){return b?!1:a.j?ca(a).then(a.V.bind(a)).then(a.X.bind(a)):a.w?a.w:!0})};
h.show=function(){var a=this.element,b=!0;void 0===b&&(b=a.hasAttribute("hidden"));b?a.removeAttribute("hidden"):a.setAttribute("hidden","");this.element.classList.add("amp-active");this.getViewport().addToFixedLayer(this.element);return this.K};h.isDismissed=function(){var a=this;return this.F?this.I.then(function(b){return b.get(a.H)}).then(function(a){return!!a},function(a){z().error("amp-user-notification","Failed to read storage",a);return!1}):Promise.resolve(!1)};
h.dismiss=function(a){var b=this;this.element.classList.remove("amp-active");this.element.classList.add("amp-hidden");this.L();this.getViewport().removeFromFixedLayer(this.element);this.F&&!a&&this.I.then(function(a){a.set(b.H,!0)});this.l&&ba(this)};
function Y(a){this.ampdoc=a;this.S=Object.create(null);this.D=Object.create(null);a=E(this.ampdoc);a=F(a);this.Y=D(a,"viewer");this.M=this.ampdoc.whenReady();this.N=Promise.all([this.Y.whenFirstVisible(),this.M]);this.W=I(F(this.ampdoc),"notificationUIManager")}Y.prototype.get=function(a){var b=this;this.N.then(function(){null==b.ampdoc.getElementById(a)&&y().warn("amp-user-notification","Did not find amp-user-notification element "+a+".")});return Z(this,a).promise};
Y.prototype.getNotification=function(a){var b=this;return this.M.then(function(){return b.S[a]})};Y.prototype.registerUserNotification=function(a,b){var c=this;this.S[a]=b;var g=Z(this,a);return this.N.then(function(){return b.shouldShow()}).then(function(a){if(a)return c.W.then(function(a){return a.registerUI(b.show.bind(b))})}).then(g.resolve.bind(this,b)).catch(w.bind(null,"Notification service failed amp-user-notification",a))};
function Z(a,b){if(a.D[b])return a.D[b];var c=new t;return a.D[b]={promise:c.promise,resolve:c.resolve}}(function(a){a.registerServiceForDoc("userNotificationManager",Y);a.registerServiceForDoc("notificationUIManager",u);a.registerElement("amp-user-notification",R,"amp-user-notification{position:fixed!important;bottom:0;left:0;overflow:hidden!important;visibility:hidden;background:hsla(0,0%,100%,0.7);z-index:1000;width:100%}amp-user-notification.amp-active{visibility:visible}amp-user-notification.amp-hidden{visibility:hidden}\n/*# sourceURL=/extensions/amp-user-notification/0.1/amp-user-notification.css*/")})(self.AMP);
})});
//# sourceMappingURL=amp-user-notification-0.1.js.map

